// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: 'https://apitest.peloton.com/v1',
  apiKey : '',
  accessToken: '',

  idpIssuer: 'https://idtest.peloton.com',
  idpClientId: 'appframe-web-api-implicit',
  idpScopes: 'appframe-web-api-implicit',
  
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR']
};